### ISSUE TITLE
Table github_workflow fails with error when we pass all repositories

### ISSUE THREAD

**Issue by madhushreeray30** [turbot/steampipe-plugin-github#388] opened 2023-12-06 05:09 UTC
**Describe the bug**
```sql
> select * from github_workflow where repository_full_name in (select name_with_owner from github_my_repository)

Error: failed to populate column 'pipeline': yaml: unmarshal errors:
  line 87: cannot unmarshal !!str `${{ fro...` into []interface {} (SQLSTATE HV000)

+-----------------------------------------------+---------------------------------------------------+----------+------------------------------------------------------------+------------------------------------>
| repository_full_name                          | name                                              | id       | path                                                       | badge_url                          >
+-----------------------------------------------+---------------------------------------------------+----------+------------------------------------------------------------+------------------------------------>
| turbot/steampipe-mod-azure-insights           | Sync Labels                                       | 00000000 | .github/workflows/sync-labels.yml                          | https://github.com/turbot/steampipe>
|                                               |                                                   |          |                                                            |                                    >
|                                               |                                                   |          |                                                            |                                    >
|                                               |                                                   |          |                                                            |                                    >
|                                               |                                                   |          |                                                            |                                    >
|                                               |                                                   |          |                                                            |                                    >
|                                               |                                                   |          |                                                            |                                    >
|                                               |                                                   |          |                                                            |                                    >
|                                               |                                                   |          |                                                            |                                    >
| turbot/steampipe-mod-azure-insights           | Stale Issues and PRs                              | 00000000 | .github/workflows/stale.yml                                | https://github.com/turbot/steampipe>
|                                               |                                                   |          |                                                            |                                    >
|                                               |                                                   |          |                                                            |                                    >
|                                               |                                                   |          |                                                            |                                    >
|                                               |                                                   |          |                                                            |                                    >
```

**Comment by gabrielsoltz** [comment] 2024-01-14 15:04
Same here. It always fails when I pass all repositories.

**Comment by ParthaI** [comment] 2024-01-15 06:05
Hello @madhushreeray30 @gabrielsoltz, Thanks for reporting the issue to us. 

I was giving a dry-run to the table and was able to reproduce the error.
At first glance, I can see the error is due to a job/workflow having an iteration over a dynamic value.

E:g.
We have a workflow that implements a matrix strategy (`matrix: ${{ fromJson(needs.get-wip-branches-set-matrix-input.outputs.wipBranches) }}`) the value is dynamic. In such a case, the table throws an error because the table code can't parse the value `${{ fromJson(needs.get-wip-branches-set-matrix-input.outputs.wipBranches) }}`.

I will have a look deeper into it and let you know.

Thanks!

**Comment by gabrielsoltz** [comment] 2024-02-11 20:36
Do you have any progress on this one @ParthaI ?

**Comment by misraved** [comment] 2024-02-14 03:52
@gabrielsoltz @ParthaI

I have been investigating the recent concerns and it appears that the root of the problem may lie with the [ArgonSecurity Pipeline Parser package](https://github.com/argonsecurity/pipeline-parser). Specifically, I am referring to the issue detailed [here](https://github.com/argonsecurity/pipeline-parser/issues/78). In an attempt to address this, I updated the package to the latest version (1.3.6), but unfortunately, it seems that this update has introduced some breaking changes.

**Comment by ParthaI** [comment] 2024-02-14 08:26
Hello @gabrielsoltz,

My apologies for the delay in resolving this issue.

I've implemented a fix addressing the problem and submitted it in [this PR](https://github.com/turbot/steampipe-plugin-github/pull/400).

The issue stemmed from workflows or jobs iterating over dynamic values, as highlighted in the [comment](https://github.com/turbot/steampipe-plugin-github/issues/388#issuecomment-1891353292) above.

After conducting tests on various workflows that incorporate iterations over dynamic values, the solution appears to be effective. The proposed code changes are currently under review.

It would be great if you would like to give it a try in the PR branch and share your experience with us.

Steps for testing the code changes in the pull request branch:
1. Clone the repository: `git clone https://github.com/turbot/steampipe-plugin-github.git`
2. Navigate into the repository directory: `cd steampipe-plugin-github`
3. Switch to the branch `issue-388`: `git checkout issue-388`
4. Execute the `make` command.
5. Execute the query.

Thank you for your patience!

**Comment by gabrielsoltz** [comment] 2024-02-14 12:30
Hi @ParthaI this is working 👌   THANK YOU

**Closed** 2024-02-14 13:46 UTC
Labels: bug
